import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { Suspense } from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const roboto = Roboto({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={roboto.className}>
          <Header />
          <main className='container mx-auto p-8 min-h-screen'>
            <Suspense fallback='Loading...'>{children}</Suspense>
          </main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
